FROM ubuntu:18.04

# defaults
RUN \
      apt-get update && apt-get install -y \
      autoconf \
      automake \
      bison \
      build-essential \
      cmake \
      curl \
      doxygen \
      flex \
      git \
      libcmocka0 \
      libcmocka-dev \
      libev-dev \
      libgtk-3-dev \
      libpcre3-dev \
      libssh-dev \
      libssl-dev \
      libtool \
      make \
      python3 \
      python3-dev \
      pkg-config \
      sudo \
      supervisor \
      swig \
      unzip \
      valgrind \
      vim \
      wget

# Adding netconf user
RUN adduser --system netconf
RUN mkdir -p /home/netconf/.ssh
RUN echo "netconf:netconf" | chpasswd && adduser netconf sudo


# Clearing and setting authorized ssh keys
RUN \
      echo '' > /home/netconf/.ssh/authorized_keys && \
      ssh-keygen -A && \
      ssh-keygen -t rsa -b 4096 -P '' -f /home/netconf/.ssh/id_rsa && \
      cat /home/netconf/.ssh/id_rsa.pub >> /home/netconf/.ssh/authorized_keys


# Updating shell to bash
RUN sed -i s#/home/netconf:/bin/false#/home/netconf:/bin/bash# /etc/passwd

RUN mkdir /opt/dev && sudo chown -R netconf /opt/dev

# set password for user (same as the username)
RUN echo "root:root" | chpasswd

# libyang
RUN \
      cd /opt/dev && \
      git clone https://github.com/CESNET/libyang.git && cd libyang && \
      git checkout devel && \
      mkdir build && cd build && \
      cmake ..                              \
        -DCMAKE_INSTALL_PREFIX=/opt/libyang \
        -DGEN_CPP_BINDINGS=1                \
        -DGEN_LANGUAGE_BINDINGS=1 &&        \
      make -j2 && \
      make install

# libnetconf2
RUN \
      cd /opt/dev && \
      git clone https://github.com/CESNET/libnetconf2.git && cd libnetconf2 && \
      git checkout devel && \
      mkdir build && cd build && \
      cmake ..                                              \
        -DCMAKE_INSTALL_PREFIX=/opt/libnetconf2             \
        -DLIBYANG_INCLUDE_DIR=/opt/libyang/include          \
        -DLIBYANG_LIBRARY=/opt/libyang/lib/libyang.so &&    \
      make -j2 && \
      make install

# sysrepo
RUN \
      cd /opt/dev && \
      git clone https://github.com/sysrepo/sysrepo.git && cd sysrepo && \
      git checkout devel && \
      mkdir build && cd build && \
      cmake ..                                                \
        -DCMAKE_C_FLAGS='-coverage -Wall'                     \
        -DCMAKE_INSTALL_PREFIX=/opt/sysrepo                   \
        -DGEN_CPP_BINDINGS=ON                                 \
        -DGEN_LANGUAGE_BINDINGS=ON                            \
        -DLIBYANG_CPP_INCLUDE_DIR=/opt/libyang/include        \
        -DLIBYANG_CPP_LIBRARY=/opt/libyang/lib/libyang-cpp.so \
        -DLIBYANG_INCLUDE_DIR=/opt/libyang/include            \
        -DLIBYANG_LIBRARY=/opt/libyang/lib/libyang.so         \
        -DREPO_PATH=/opt/sysrepo-repository &&                \
      make -j2 && \
      make install

# netopeer 2
RUN \
      export LD_LIBRARY_PATH=/opt/sysrepo/lib:/opt/libyang/lib:/opt/libnetconf2/libnetconf2 && \
      cd /opt/dev && \
      git clone https://github.com/CESNET/Netopeer2.git && cd Netopeer2 && \
      git checkout devel-server && \
      cd /opt/dev/Netopeer2/server && \
      mkdir build && cd build && \
      cmake ..                                                    \
        -DCMAKE_INSTALL_PREFIX=/opt/Netopeer2                     \
        -DCMAKE_PREFIX_PATH=/opt/sysrepo                          \
        -DENABLE_CONFIGURATION=ON                                 \
        -DKEYSTORED_KEYS_DIR=/opt/Netopeer2/keystored/keys        \
        -DLIBNETCONF2_INCLUDE_DIR=/opt/libnetconf2/include        \
        -DLIBNETCONF2_LIBRARY=/opt/libnetconf2/lib/libnetconf2.so \
        -DLIBYANG_INCLUDE_DIR=/opt/libyang/include                \
        -DLIBYANG_LIBRARY=/opt/libyang/lib/libyang.so             \
        -DSR_PLUGINS_DIR=/opt/sysrepo/lib/sysrepo/plugins         \
        -DSYSREPO_INCLUDE_DIR=/opt/sysrepo/include                \
        -DSYSREPO_LIBRARY=/opt/sysrepo/lib/libsysrepo.so          \
        -DSYSREPOCFG_EXECUTABLE=/opt/sysrepo/bin/sysrepocfg       \
        -DSYSREPOCTL_EXECUTABLE=/opt/sysrepo/bin/sysrepoctl &&    \
      make -j2 && \
      make install

RUN \
      export LD_LIBRARY_PATH=/opt/sysrepo/lib:/opt/libyang/lib:/opt/libnetconf2/libnetconf2 && \
      cd /opt/dev/Netopeer2/cli && \
      mkdir build && cd build && \
      cmake ..                                                    \
        -DCMAKE_INSTALL_PREFIX=/opt/Netopeer2                     \
        -DCMAKE_PREFIX_PATH=/opt/sysrepo                          \
        -DENABLE_CONFIGURATION=ON                                 \
        -DKEYSTORED_KEYS_DIR=/opt/Netopeer2/keystored/keys        \
        -DLIBNETCONF2_INCLUDE_DIR=/opt/libnetconf2/include        \
        -DLIBNETCONF2_LIBRARY=/opt/libnetconf2/lib/libnetconf2.so \
        -DLIBYANG_INCLUDE_DIR=/opt/libyang/include                \
        -DLIBYANG_LIBRARY=/opt/libyang/lib/libyang.so             \
        -DSR_PLUGINS_DIR=/opt/sysrepo/lib/sysrepo/plugins         \
        -DSYSREPO_INCLUDE_DIR=/opt/sysrepo/include                \
        -DSYSREPO_LIBRARY=/opt/sysrepo/lib/libsysrepo.so          \
        -DSYSREPOCFG_EXECUTABLE=/opt/sysrepo/bin/sysrepocfg       \
        -DSYSREPOCTL_EXECUTABLE=/opt/sysrepo/bin/sysrepoctl &&    \
      make -j2 && \
      make install

ENV EDITOR vim
EXPOSE 830

COPY supervisord.conf /etc/supervisord.conf
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
